## Atividade Prática 2: Representações em Espaços Vetoriais

### Nome:  Ciro B Rosa

### N⁰ USP:  2320769

Nessa tarefa exploraremos as transformações resultantes de mudar a base de representação de vetores em um espaço vetorial. 

### Revisão do conceito de base

Uma *base* de um espaço vetorial $V$ é um conjunto $S$ em $V$ que tem as duas propriedades a seguir:

- $S$ é um *conjunto gerador* para $V$, ou seja, $S$ permite representar qualquer $x\in V$ através de uma equação
$$x=\sum_{i=0}^{K-1}a_iv_i$$
onde $a_i$ são escalares e $v_i\in S,\ \forall i$.

- $S$ é *linearmente independente*, ou seja, não existem vetores em $S$ "redundantes"; em matematiquês isso equivale a dizer que qualquer sistema da forma
$$\sum_{i=0}^{K-1}a_iv_i=0$$
com $v_i\in S$ só admite a solução trivial $a_i=0,\ \forall i$.

Se $S$ é uma base finita para $V$, o tamanho $N=|S|$ de $S$ é denominado **dimensão** de $V$ (e é possível provar que qualquer outra base de $V$ também possui exatamente $N$ elementos).

__Exemplo:__ a base canônica de $\mathbb{R}^N$ ou $\mathbb{C}^N$ é formada pelos vetores $e_i=\left(0,\ldots,0,\overbrace{1}^{i},0,\ldots,0\right)$, que são geradores desses espaços (por construção), e linearmente independentes, pois $\displaystyle\sum_{i=0}^{K-1}a_ie_i=(a_0,a_1,\ldots,a_{N-1})=(0,0,\ldots,0)$ implica imediatamente $a_i=0,\ \forall i$.

Uma propriedade importante dessa base é que ela é *ortogonal*, ou seja, que $(e_i,e_j)=\sum_{k=0}^{N-1}(e_i)_k(e_j)_k=0,\ \forall i\neq j$.

### Bases e ortogonalidade

Em um espaço $N$ dimensional, qualquer conjunto ortogonal de $N$ vetores não-nulos é necessariamente uma base. Isso decorre do fato de que se $S=\{v_0,v_1,\ldots,v_{N-1}\}$ com $v_i\neq 0,\ \forall i$ e $(v_i,v_j)=0,\ \forall v_i,v_j\in S,\ i\neq j$, então o sistema
$\displaystyle\sum_{i=0}^{K-1}a_iv_i=0$ pode ser resolvido fazendo produtos internos com cada $v_j$:
$$\displaystyle\left(\sum_{i=0}^{K-1}a_iv_i,v_j\right) = \sum_{i=0}^{K-1}a_i(v_i,v_j) = a_j(v_j,v_j) = 0,$$
onde o somatório desaparece porque $(v_i,v_j)=0$ para todo $i\neq j$, e como $(v_j,v_j)=\|v_j\|^2\neq 0$ segue que $a_j=0$ (esse argumento vale $\forall j$).

### Mudanças de base

Se $S$ é uma base qualquer para $V$, temos uma garantia de que é possível representar qualquer $x\in V$ como $x=\displaystyle\sum_{i=0}^{K-1}a_iv_i$ (Eq. I). Uma pergunta razoável é: "como encontrar os $a_i$'s?".

Uma solução muito simples existe quando $S$ é uma base ortogonal: nesse caso, podemos proceder outra vez por eliminação, fazendo  produtos internos da Eq. I com cada $v_j$:
$$(x,v_j) = \left(\sum_{i=0}^{K-1}a_iv_i,v_j\right) = \sum_{i=0}^{K-1}a_i(v_i,v_j) = a_j(v_j,v_j),$$
de onde segue que
$$a_j=\frac{(x,v_j)}{(v_j,v_j)}$$
(observe que como $S$ é base, $0\not\in S$ e portanto $(v_j,v_j)=\|v_j\|^2\neq 0,\ \forall v_j\in S$).

#### Dependências dessa tarefa

In [1]:
import math as m
import numpy as np

#### Exercício 1: Considere o conjunto $S=\{v_1,v_2,v_3\}\subset\mathbb{R}^3$ com $v_1=(1,1,0)$, $v_2=(-1,1,1)$ e $v_3=(1,-1,2)$.

(a) Escreva um código que verifique que $S$ é ortogonal com respeito ao produto interno canônico $\displaystyle(x,y)=\sum_{i=0}^2x_iy_i$. Como $|S|=3$, isso mostrará que $S$ é uma base para $\mathbb{R}^3$.

In [2]:
# Exercício 1(a)
# Dicas: use sempre arrays do numpy com valores float,
# por exemplo v = np.array([[1.,0.],[0.,1.]]) ou v = np.array([[1,0],[0,1]],dtype=float);
# use a função np.inner(x,y) para computar (x,y),
# e o comando "assert np.linalg.norm(z)<1e-12" para checar se ||z||=0.
v1 = np.array((1, 1, 0))
v2 = np.array((-1, 1, 1))
v3 = np.array((1, -1, 2))

S = np.array((v1, v2, v3), dtype = float)
nVectors = np.shape(S)[0]
print("base S: \n", S)

innerProducts = [np.inner(S[k, :], S[l, :]) for k in range(0, nVectors-1) for l in range(k+1, nVectors)]
print("\nprodutos internos:", innerProducts)

# compara se o vetor z é próximo de zero
def nearZeroVector(z):
    return (np.linalg.norm(z) < 1e-12)

print("\ntodos os produtos internos iguais a zero:", nearZeroVector(innerProducts))


base S: 
 [[ 1.  1.  0.]
 [-1.  1.  1.]
 [ 1. -1.  2.]]

produtos internos: [0.0, 0.0, 0.0]

todos os produtos internos iguais a zero: True


(b) Escreva um código que compute os coeficientes $a_1,a_2,a_3$ da representação de $x=(3,4,5)$ em relação à base $S$, e que verifique que a expressão $\displaystyle x=\sum_{k=1}^3a_kv_k=a_1v_1+a_2v_2+a_3v_3$ de fato é satisfeita.

In [3]:
# Exercício 1(b)
x = np.array((3, 4, 5), dtype=float)
print("vetor x: ", x)

num = np.inner(x, S)
den = np.diagonal(np.inner(S, S))
a = num / den
x_hat = np.sum((a * S.T), axis=1)

print("coeficientes a: ", a)
print("vetor x_hat é igual ao vetor x: ", nearZeroVector(x - x_hat))


vetor x:  [3. 4. 5.]
coeficientes a:  [3.5 2.  1.5]
vetor x_hat é igual ao vetor x:  True


(c) Escreva um código que compute os vetores *normalizados* $S'=\{v'_1,v'_2,v'_3\}$ onde $v'_i=\frac{v_i}{\|v_i\|}$, e depois compute os coeficientes $a'_1,a'_2,a'_3$ da representação de $x=(3,4,5)$ em relação à base $S'$, verificando que a expressão $x=a'_1v'_1+a'_2v'_2+a'_3v'_3$ de fato é satisfeita.

(Obs: uma base ortogonal e normalizada é chamada de *base ortonormal*).

In [4]:
# Exercício 1(c)
print("vetor x: ", x)
print("\nbase S: \n", S)

S_linha = S.T / np.sqrt(np.diagonal(np.inner(S, S)))
S_linha = S_linha.T
print("\nbase ortonormal S': \n", S_linha)
print("\nnorma unitária para vetores de S': ", np.linalg.norm(S_linha, axis=1))

num = np.inner(x, S_linha)
den = np.diagonal(np.inner(S_linha, S_linha))
a_linha = num / den
x_hat = np.sum((a_linha * S_linha.T), axis=1)

print("\ncoeficientes a': ", a_linha)
print("vetor x_hat é igual ao vetor x: ", nearZeroVector(x - x_hat))


vetor x:  [3. 4. 5.]

base S: 
 [[ 1.  1.  0.]
 [-1.  1.  1.]
 [ 1. -1.  2.]]

base ortonormal S': 
 [[ 0.70710678  0.70710678  0.        ]
 [-0.57735027  0.57735027  0.57735027]
 [ 0.40824829 -0.40824829  0.81649658]]

norma unitária para vetores de S':  [1. 1. 1.]

coeficientes a':  [4.94974747 3.46410162 3.67423461]
vetor x_hat é igual ao vetor x:  True


(d) Escreva um código que verifique que $\|x\|^2=\|a'\|^2$ (ou equivalentemente $x_1^2+x_2^2+x_3^2=a_1'^2+a_2'^2+a_3'^2$).

Esse resultado é conhecido como *Equação de Parseval*, que estabelece que as representações $(x_1,x_2,x_3)$ e $(a'_1,a'_2,a'_3)$ têm o mesmo "tamanho" (e assim a transformação $x\mapsto a'$ é uma *isometria*).

In [5]:
# Exercício 1(d)
print(np.square(np.linalg.norm(x)))
print(np.square(np.linalg.norm(a_linha)))

nearZeroVector(np.square(np.linalg.norm(x)) - np.square(np.linalg.norm(a_linha)))

50.00000000000001
49.99999999999999


True

#### Exercício 2: Considere o conjunto $S=\{E_0,E_1,E_2,E_3\}$ onde $E_k\in\mathbb{C}^4$ é o vetor definido por $$(E_k)_n=e^{i2\pi kn/4},\ n=0,1,2,3.$$ Veremos que esse conjunto é ortogonal, e portanto $S$ é uma base de $\mathbb{C}^4$.

(a) Use a mesma estratégia do Exercício 1(a) para verificar computacionalmente que esses vetores são de fato ortogonais em relação ao produto interno canônico $\displaystyle(x,y)=\sum_{i=0}^3x_i\overline{y_i}$.

In [6]:
# Exercício 2(a)
# Dica: compute os produtos internos (x,y) como np.inner(x,np.conjugate(y))
n = np.arange(0, 4)

E0 = np.exp(1j * 2 * m.pi * 0 * n / 4)
E1 = np.exp(1j * 2 * m.pi * 1 * n / 4)
E2 = np.exp(1j * 2 * m.pi * 2 * n / 4)
E3 = np.exp(1j * 2 * m.pi * 3 * n / 4)

E = np.array((E0, E1, E2, E3), dtype=complex)
nVectors = np.shape(E)[0]
print("base E: \n", E)

innerProducts = [np.inner(E[k, :], np.conjugate(E[l, :])) for k in range(0, nVectors-1) for l in range(k+1, nVectors)]
innerProducts = np.array(innerProducts)
print("\nprodutos internos:\n", innerProducts)
print("\ntodos os produtos internos iguais a zero:", nearZeroVector(innerProducts))

base E: 
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]

produtos internos:
 [-1.83697020e-16-2.22044605e-16j  0.00000000e+00-2.44929360e-16j
  3.29046455e-16-3.33066907e-16j -1.72254642e-16-1.33907057e-16j
  0.00000000e+00-2.44929360e-16j -8.41170949e-17-1.99159850e-16j]

todos os produtos internos iguais a zero: True


(b) Use a mesma estratégia do Exercício 1(b) para escrever $v=(1,5,-2,3)$ como combinação linear dos elementos de $S$, ou seja, escreva um código para computar os coeficientes $a_k$ tais que $\displaystyle v=\sum_{k=0}^3a_kE_k$ e verificar automaticamente essa equação.

In [7]:
# Exercício 2(b)
# Dica: use somente vetores numpy complexos, fazendo v = np.array(...,dtype=complex)
v = np.array((1, 5, -2, 3), dtype=complex)
print("vetor v: ", v)

num = np.inner(v, np.conjugate(E))
den = np.diagonal(np.inner(E, np.conjugate(E)))
a = num / den
v_hat = np.sum((a * E.T), axis=1)

print("\ncoeficientes a: ", a)
print("\nvetor v_hat é igual ao vetor v: ", nearZeroVector(v - v_hat))


vetor v:  [ 1.+0.j  5.+0.j -2.+0.j  3.+0.j]

coeficientes a:  [ 1.75+0.0000000e+00j  0.75-5.0000000e-01j -2.25-5.5109106e-16j
  0.75+5.0000000e-01j]

vetor v_hat é igual ao vetor v:  True


(c) Use a mesma estratégia do Exercício 1(c) para normalizar os vetores $E_k$ (obtendo vetores $E'_k$ e uma base ortonormal $S'$) e use-os para escrever $v=(1,5,-2,3)$ como combinação linear dos elementos de $S'$, ou seja, escreva um código para computar os coeficientes $a'_k$ tais que $\displaystyle v=\sum_{k=0}^3a'_kE'_k$ e verificar automaticamente essa equação.

In [8]:
# Exercício 2(c)
print("vetor v: ", v)
print("\nbase E: \n", E)

E_linha = E.T / np.sqrt(np.diagonal(np.inner(E, np.conjugate(E))))
E_linha = E_linha.T
print("\nbase ortonormal E': \n", E_linha)
print("\nnorma unitária para vetores de E': ", np.linalg.norm(E_linha, axis=1))

num = np.inner(v, np.conjugate(E_linha))
den = np.diagonal(np.inner(E_linha, np.conjugate(E_linha)))
a_linha = num / den
v_hat = np.sum((a_linha * E_linha.T), axis=1)

print("\ncoeficientes a': ", a_linha)
print("\nvetor v_hat é igual ao vetor v: ", nearZeroVector(v - v_hat))


vetor v:  [ 1.+0.j  5.+0.j -2.+0.j  3.+0.j]

base E: 
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]

base ortonormal E': 
 [[ 5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j
   5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j]
 [ 5.00000000e-01+0.0000000e+00j  3.06161700e-17+5.0000000e-01j
  -5.00000000e-01+6.1232340e-17j -9.18485099e-17-5.0000000e-01j]
 [ 5.00000000e-01+0.0000000e+00j -5.00000000e-01+6.1232340e-17j
   5.00000000e-01-1.2246468e-16j -5.00000000e-01+1.8369702e-16j]
 [ 5.00000000e-01+0.0000000e+00j -

(d) Use a mesma estratégia do Exercício 1(d) para verificar que $\|v\|^2=\|a'\|^2$.

In [9]:
# Exercício 2(d)
print(np.square(np.linalg.norm(v)))
print(np.square(np.linalg.norm(a_linha)))

nearZeroVector(np.square(np.linalg.norm(v)) - np.square(np.linalg.norm(a_linha)))

39.0
39.0


True